version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gosec
    - bodyclose
    - gocritic
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - whyNoLint
        - hugeParam
        - ifElseChain
        - octalLiteral
        - emptyStringTest
        - sprintfQuotedString
        - unnamedResult
        - appendCombine
