version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - bodyclose
    - exportloopref
    - gocritic
    - noctx

linter-settings:
  govet:
    enable-all: true
    disable:
      - shadow

  revive:
    confidence: 0.8

  gosec:
    excludes:
      - G204

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentFormatting
      - whyNoLint

issues:
  exclude:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic
    - path: internal/mocks/
      linters:
        - unused

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
