// Copyright 2025 Logan Lindquist Land
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package commands

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// NewInitCommand creates the init command
func NewInitCommand(configPath *string) *cobra.Command {
	var global bool

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize PRGuard configuration",
		Long:  `Creates a new configuration file with interactive prompts`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runInit(global)
		},
	}

	cmd.Flags().BoolVar(&global, "global", true, "Create config in ~/.config/prguard/ (default: true)")

	return cmd
}

func runInit(global bool) error {
	reader := bufio.NewReader(os.Stdin)

	// Determine config path
	configPath, err := determineConfigPath(global)
	if err != nil {
		return err
	}

	// Check if config already exists and prompt for overwrite
	shouldProceed, err := promptOverwriteExisting(configPath, reader)
	if err != nil {
		return err
	}
	if !shouldProceed {
		return nil
	}

	fmt.Println("=== PRGuard Configuration Setup ===")
	fmt.Println()

	// Get GitHub username from git config
	gitUser := getGitConfigValue("github.user")
	if gitUser == "" {
		gitUser = getGitConfigValue("user.name")
	}

	// Prompt for GitHub token
	token, err := promptGitHubToken(reader)
	if err != nil {
		return err
	}

	// Prompt for org or user
	org, user, err := promptOrgOrUser(reader, gitUser)
	if err != nil {
		return err
	}

	// Prompt for repositories (optional)
	repos, err := promptRepositories(reader)
	if err != nil {
		return err
	}

	// Build config content
	config := buildConfig(token, org, user, repos, global)

	// Write config file
	if err := writeConfigFile(configPath, config); err != nil {
		return err
	}

	// Display success message
	displayInitSuccess(configPath)

	return nil
}

func buildConfig(token, org, user string, repos []string, global bool) string {
	var sb strings.Builder

	sb.WriteString("# PRGuard Configuration\n")
	sb.WriteString("# Generated by: prguard init\n\n")

	// GitHub section
	sb.WriteString("github:\n")
	sb.WriteString(fmt.Sprintf("  token: \"%s\"\n", token))
	if org != "" {
		sb.WriteString(fmt.Sprintf("  org: \"%s\"\n", org))
	} else {
		sb.WriteString(fmt.Sprintf("  user: \"%s\"\n", user))
	}
	sb.WriteString("\n")

	// Database section
	sb.WriteString("database:\n")
	sb.WriteString("  type: \"sqlite\"\n")
	if global {
		home, _ := os.UserHomeDir()
		dbPath := filepath.Join(home, ".local", "prguard", "prguard.db")
		sb.WriteString(fmt.Sprintf("  path: \"%s\"\n", dbPath))
	} else {
		sb.WriteString("  path: \"./prguard.db\"\n")
	}
	sb.WriteString("\n")

	// Repositories section (if any)
	if len(repos) > 0 {
		sb.WriteString("# Repositories to monitor\n")
		sb.WriteString("repositories:\n")
		for _, repo := range repos {
			parts := strings.Split(repo, "/")
			sb.WriteString(fmt.Sprintf("  - owner: \"%s\"\n", parts[0]))
			sb.WriteString(fmt.Sprintf("    name: \"%s\"\n", parts[1]))
		}
		sb.WriteString("\n")
	}

	// Filters section with sensible defaults
	sb.WriteString("# Spam detection filters\n")
	sb.WriteString("filters:\n")
	sb.WriteString("  min_files: 2\n")
	sb.WriteString("  min_lines: 10\n")
	sb.WriteString("  account_age_days: 7\n")
	sb.WriteString("  readme_only_block: true\n")
	sb.WriteString("  \n")
	sb.WriteString("  # Whitelist trusted bots\n")
	sb.WriteString("  whitelist:\n")
	sb.WriteString("    - \"dependabot[bot]\"\n")
	sb.WriteString("    - \"renovate[bot]\"\n")
	sb.WriteString("  \n")
	sb.WriteString("  # Common spam phrases (add your own)\n")
	sb.WriteString("  spam_phrases:\n")
	sb.WriteString("    - \"click here\"\n")
	sb.WriteString("    - \"visit my site\"\n")
	sb.WriteString("    - \"check out\"\n")
	sb.WriteString("\n")

	// Blocklist section
	sb.WriteString("# Blocklist management\n")
	sb.WriteString("blocklist:\n")
	sb.WriteString("  auto_export: false\n")
	if global {
		home, _ := os.UserHomeDir()
		exportPath := filepath.Join(home, ".local", "prguard", "exports")
		sb.WriteString(fmt.Sprintf("  export_path: \"%s\"\n", exportPath))
	} else {
		sb.WriteString("  export_path: \"./exports\"\n")
	}
	sb.WriteString("  \n")
	sb.WriteString("  # Remote blocklist sources (optional)\n")
	sb.WriteString("  # sources:\n")
	sb.WriteString("  #   - name: \"Community Blocklist\"\n")
	sb.WriteString("  #     url: \"https://example.com/blocklist.json\"\n")
	sb.WriteString("  #     trusted: true\n")
	sb.WriteString("  #     auto_sync: false\n")
	sb.WriteString("\n")

	// Actions section
	sb.WriteString("# Default actions\n")
	sb.WriteString("actions:\n")
	sb.WriteString("  close_prs: false\n")
	sb.WriteString("  block_users: false\n")
	sb.WriteString("  add_spam_label: true\n")
	sb.WriteString("  comment_template: |\n")
	sb.WriteString("    This PR has been flagged as potential spam and closed.\n")
	sb.WriteString("    If you believe this is an error, please contact the maintainers.\n")

	return sb.String()
}

// getGitConfigValue reads a value from git config
func getGitConfigValue(key string) string {
	cmd := exec.Command("git", "config", "--get", key)
	output, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(output))
}
