package commands

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// NewInitCommand creates the init command
func NewInitCommand(configPath *string) *cobra.Command {
	var global bool

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize PRGuard configuration",
		Long:  `Creates a new configuration file with interactive prompts`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runInit(global)
		},
	}

	cmd.Flags().BoolVar(&global, "global", true, "Create config in ~/.config/prguard/ (default: true)")

	return cmd
}

func runInit(global bool) error {
	reader := bufio.NewReader(os.Stdin)

	// Determine config path
	var configPath string
	if global {
		home, err := os.UserHomeDir()
		if err != nil {
			return fmt.Errorf("failed to get home directory: %w", err)
		}
		configDir := filepath.Join(home, ".config", "prguard")
		configPath = filepath.Join(configDir, "config.yaml")
	} else {
		configPath = "./config.yaml"
	}

	// Check if config already exists
	if _, err := os.Stat(configPath); err == nil {
		fmt.Printf("Config file already exists at: %s\n", configPath)
		fmt.Print("Overwrite? (y/N): ")
		response, _ := reader.ReadString('\n')
		response = strings.TrimSpace(strings.ToLower(response))
		if response != "y" && response != "yes" {
			fmt.Println("Initialization cancelled.")
			return nil
		}
	}

	fmt.Println("=== PRGuard Configuration Setup ===")
	fmt.Println()

	// Get GitHub username from git config
	gitUser := getGitConfigValue("github.user")
	if gitUser == "" {
		gitUser = getGitConfigValue("user.name")
	}

	// Prompt for GitHub token
	fmt.Println("GitHub Personal Access Token:")
	fmt.Println("  Create one at: https://github.com/settings/tokens")
	fmt.Println("  Required scopes: repo, write:discussion")
	fmt.Print("Token: ")
	token, _ := reader.ReadString('\n')
	token = strings.TrimSpace(token)

	if token == "" {
		return fmt.Errorf("GitHub token is required")
	}

	// Prompt for org or user
	fmt.Println("\nGitHub Organization or User:")
	if gitUser != "" {
		fmt.Printf("  Detected from git config: %s\n", gitUser)
	}
	fmt.Print("Enter org name (or press Enter for user mode): ")
	org, _ := reader.ReadString('\n')
	org = strings.TrimSpace(org)

	var user string
	if org == "" {
		if gitUser != "" {
			fmt.Printf("Use '%s' as username? (Y/n): ", gitUser)
			response, _ := reader.ReadString('\n')
			response = strings.TrimSpace(strings.ToLower(response))
			if response == "" || response == "y" || response == "yes" {
				user = gitUser
			}
		}

		if user == "" {
			fmt.Print("GitHub username: ")
			user, _ = reader.ReadString('\n')
			user = strings.TrimSpace(user)
		}

		if user == "" {
			return fmt.Errorf("either org or user is required")
		}
	}

	// Prompt for repositories (optional)
	fmt.Println("\nRepositories to monitor (optional):")
	fmt.Println("  Enter repositories in 'owner/repo' format, one per line")
	fmt.Println("  Press Enter on empty line to finish")

	var repos []string
	for {
		fmt.Print("Repository (or Enter to skip): ")
		repo, _ := reader.ReadString('\n')
		repo = strings.TrimSpace(repo)

		if repo == "" {
			break
		}

		// Validate format
		parts := strings.Split(repo, "/")
		if len(parts) != 2 {
			fmt.Println("  Invalid format. Use: owner/repo")
			continue
		}

		repos = append(repos, repo)
	}

	// Build config content
	config := buildConfig(token, org, user, repos, global)

	// Create directory if needed
	dir := filepath.Dir(configPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Write config file
	if err := os.WriteFile(configPath, []byte(config), 0600); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	fmt.Printf("\n✓ Configuration created at: %s\n", configPath)
	fmt.Println("\nNext steps:")
	fmt.Println("  1. Review and edit the config file if needed")
	fmt.Println("  2. Run: prguard scan owner/repo")
	fmt.Println("  3. Or: prguard scan-all (if you added repositories)")

	return nil
}

func buildConfig(token, org, user string, repos []string, global bool) string {
	var sb strings.Builder

	sb.WriteString("# PRGuard Configuration\n")
	sb.WriteString("# Generated by: prguard init\n\n")

	// GitHub section
	sb.WriteString("github:\n")
	sb.WriteString(fmt.Sprintf("  token: \"%s\"\n", token))
	if org != "" {
		sb.WriteString(fmt.Sprintf("  org: \"%s\"\n", org))
	} else {
		sb.WriteString(fmt.Sprintf("  user: \"%s\"\n", user))
	}
	sb.WriteString("\n")

	// Database section
	sb.WriteString("database:\n")
	sb.WriteString("  type: \"sqlite\"\n")
	if global {
		home, _ := os.UserHomeDir()
		dbPath := filepath.Join(home, ".local", "prguard", "prguard.db")
		sb.WriteString(fmt.Sprintf("  path: \"%s\"\n", dbPath))
	} else {
		sb.WriteString("  path: \"./prguard.db\"\n")
	}
	sb.WriteString("\n")

	// Repositories section (if any)
	if len(repos) > 0 {
		sb.WriteString("# Repositories to monitor\n")
		sb.WriteString("repositories:\n")
		for _, repo := range repos {
			parts := strings.Split(repo, "/")
			sb.WriteString(fmt.Sprintf("  - owner: \"%s\"\n", parts[0]))
			sb.WriteString(fmt.Sprintf("    name: \"%s\"\n", parts[1]))
		}
		sb.WriteString("\n")
	}

	// Filters section with sensible defaults
	sb.WriteString("# Spam detection filters\n")
	sb.WriteString("filters:\n")
	sb.WriteString("  min_files: 2\n")
	sb.WriteString("  min_lines: 10\n")
	sb.WriteString("  account_age_days: 7\n")
	sb.WriteString("  readme_only_block: true\n")
	sb.WriteString("  \n")
	sb.WriteString("  # Whitelist trusted bots\n")
	sb.WriteString("  whitelist:\n")
	sb.WriteString("    - \"dependabot[bot]\"\n")
	sb.WriteString("    - \"renovate[bot]\"\n")
	sb.WriteString("  \n")
	sb.WriteString("  # Common spam phrases (add your own)\n")
	sb.WriteString("  spam_phrases:\n")
	sb.WriteString("    - \"click here\"\n")
	sb.WriteString("    - \"visit my site\"\n")
	sb.WriteString("    - \"check out\"\n")
	sb.WriteString("\n")

	// Blocklist section
	sb.WriteString("# Blocklist management\n")
	sb.WriteString("blocklist:\n")
	sb.WriteString("  auto_export: false\n")
	if global {
		home, _ := os.UserHomeDir()
		exportPath := filepath.Join(home, ".local", "prguard", "exports")
		sb.WriteString(fmt.Sprintf("  export_path: \"%s\"\n", exportPath))
	} else {
		sb.WriteString("  export_path: \"./exports\"\n")
	}
	sb.WriteString("  \n")
	sb.WriteString("  # Remote blocklist sources (optional)\n")
	sb.WriteString("  # sources:\n")
	sb.WriteString("  #   - name: \"Community Blocklist\"\n")
	sb.WriteString("  #     url: \"https://example.com/blocklist.json\"\n")
	sb.WriteString("  #     trusted: true\n")
	sb.WriteString("  #     auto_sync: false\n")
	sb.WriteString("\n")

	// Actions section
	sb.WriteString("# Default actions\n")
	sb.WriteString("actions:\n")
	sb.WriteString("  close_prs: false\n")
	sb.WriteString("  add_spam_label: true\n")
	sb.WriteString("  comment_template: |\n")
	sb.WriteString("    This PR has been flagged as potential spam and closed.\n")
	sb.WriteString("    If you believe this is an error, please contact the maintainers.\n")

	return sb.String()
}

// getGitConfigValue reads a value from git config
func getGitConfigValue(key string) string {
	cmd := exec.Command("git", "config", "--get", key)
	output, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(output))
}
